/**
 * 无边框窗口自绘 chrome：向 dsh web UI 页面注入的 CSS 与 JS。
 *
 * 独立成文件、用普通字符串拼接（避免在主逻辑中嵌多层模板字符串）。
 *
 * 负责：
 *  - 窗口圆角（transparent + 根容器 border-radius）
 *  - 顶部拖拽条 + 双击最大化/还原
 *  - 右上角自定义最小化/最大化/关闭按钮（Windows/Linux）
 *  - 左上角 macOS 信号灯（红黄绿），并给左侧栏顶部让位
 *  - Session log 按钮左移，给窗口控制按钮让位
 *  - 最大化时取消圆角
 *
 * 平台判定：window.__DSH_DESKTOP__.platform（preload 注入，darwin/win32/linux）。
 * 注入代码是给「浏览器页面」执行的，window.__dshDesktop 由 preload 暴露。
 */

/** 注入到页面 <head> 的样式（普通字符串，无模板插值）。 */
export const DESKTOP_CHROME_CSS = [
  // 方案二：透明窗口 + CSS 阴影。body 四周留 20px 透明边距（阴影透出），
  // #root 内缩成带圆角的“卡片”，box-shadow 投影在透明边距区。
  'html, body { background: transparent !important; }',
  'html, body { height: 100%; box-sizing: border-box; }',
  'body { padding: 20px; }',
  '#root, [data-slot="root"], .dsh-kit-app-root {',
  '  height: 100%;',
  '  border-radius: 12px;',
  '  overflow: hidden;',
  '  box-shadow: 0 8px 30px rgba(0, 0, 0, 0.35);',
  '}',
  '',
  '/* 顶部自绘标题栏（拖拽区；从内容边缘开始） */',
  '.dshkit-dragbar {',
  '  position: fixed;',
  '  top: 20px; left: 20px; right: 20px;',
  '  height: 38px;',
  '  -webkit-app-region: drag;',
  '  z-index: 2147483646;',
  '  pointer-events: auto;',
  '}',
  '/* 非 mac：右侧让出右上角控制按钮区域，避免 drag 与 no-drag 重叠挡点击 */',
  'body:not([data-dsh-platform="darwin"]) .dshkit-dragbar {',
  '  right: 165px;',
  '}',
  '/* mac：左侧让出信号灯区域，避免 drag 与 no-drag 重叠挡点击 */',
  'body[data-dsh-platform="darwin"] .dshkit-dragbar {',
  '  left: 90px;',
  '}',
  '',
  '/* ---- macOS：左上角信号灯（贴内容左上角） ---- */',
  '.dshkit-trafficlights {',
  '  position: fixed;',
  '  top: calc(20px + 12px); left: calc(20px + 14px);',
  '  height: 20px;',
  '  display: none;',
  '  align-items: center;',
  '  gap: 8px;',
  '  -webkit-app-region: no-drag;',
  '  z-index: 2147483647;',
  '}',
  '.dshkit-trafficlights button {',
  '  width: 12px;',
  '  height: 12px;',
  '  border: none;',
  '  border-radius: 50%;',
  '  padding: 0;',
  '  cursor: default;',
  '  display: block;',
  '}',
  '.dshkit-trafficlights button.dshkit-tl-close { background: #ff5f57; }',
  '.dshkit-trafficlights button.dshkit-tl-min { background: #febc2e; }',
  '.dshkit-trafficlights button.dshkit-tl-max { background: #28c840; }',
  '',
  '/* 平台开关 */',
  'body[data-dsh-platform="darwin"] .dshkit-winctl { display: none; }',
  'body[data-dsh-platform="darwin"] .dshkit-trafficlights { display: flex; }',
  'body[data-dsh-platform="darwin"] [class*="sidebarCol"] {',
  '  padding-top: 40px !important;',
  '}',
  '',
  '/* ---- Windows/Linux：右上角控制按钮（贴内容右上角） ---- */',
  '.dshkit-winctl {',
  '  position: fixed;',
  '  top: 20px; right: 20px;',
  '  height: 30px;',
  '  display: flex;',
  '  align-items: stretch;',
  '  gap: 2px;',
  '  padding-right: 0;',
  '  -webkit-app-region: no-drag;',
  '  z-index: 2147483647;',
  '  user-select: none;',
  '}',
  '.dshkit-winctl button {',
  '  width: 42px;',
  '  height: 30px;',
  '  border: none;',
  '  background: transparent;',
  '  color: var(--dsw-alias-label-primary, #e8ecf4);',
  '  border-radius: 0;',
  '  font-size: 14px;',
  '  line-height: 1;',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  cursor: default;',
  '  transition: background-color .12s ease;',
  '}',
  '/* 与窗口轮廓一致：关闭按钮右上角跟随卡片 12px 圆角，其余直角 */',
  '.dshkit-winctl button.dshkit-close { border-radius: 0 12px 0 0; }',
  '.dshkit-winctl button:hover { background: rgba(127,127,127,.18); }',
  '.dshkit-winctl button.dshkit-close:hover { background: rgba(232,17,35,.85); color: #fff; }',
  '',
  '/* Session log 按钮往左移：给右上角控制按钮让位（仅非 mac 需要） */',
  'body:not([data-dsh-platform="darwin"]) [class*="headerUtilities"] {',
  '  margin-right: 128px;',
  '}',
  '',
  '/* 最大化时取消边距/圆角/阴影（贴满屏幕，避免露出透明边与桌面） */',
  'body.dshkit-maximized { padding: 0 !important; }',
  'body.dshkit-maximized #root,',
  'body.dshkit-maximized [data-slot="root"] {',
  '  border-radius: 0 !important;',
  '  box-shadow: none !important;',
  '}',
  '/* 最大化时：dragbar 顶部归零；让位值（right:165 / left:90）保持生效避免重叠 */',
  'body.dshkit-maximized .dshkit-dragbar { top: 0; }',
  'body.dshkit-maximized .dshkit-winctl { top: 0; right: 0; }',
  'body.dshkit-maximized .dshkit-winctl button.dshkit-close { border-radius: 0; }',
  'body.dshkit-maximized .dshkit-trafficlights { top: 12px; left: 14px; }',
].join('\n')

/** 注入到页面执行的脚本（普通字符串，无模板插值）。 */
export const DESKTOP_CHROME_JS = [
  '(function () {',
  '  if (window.__dshKitDesktopChrome__) return',
  '  window.__dshKitDesktopChrome__ = true',
  '',
  '  var style = document.createElement("style")',
  '  style.setAttribute("data-dsh-kit", "desktop-chrome")',
  '  style.textContent = window.__DSH_DESKTOP_CHROME_CSS__ || ""',
  '  document.head.appendChild(style)',
  '',
  '  /* 平台标记（darwin / win32 / linux） */',
  '  var platform = (window.__DSH_DESKTOP__ && window.__DSH_DESKTOP__.platform) || ""',
  '  document.body.setAttribute("data-dsh-platform", platform)',
  '  var isMac = platform === "darwin"',
  '',
  '  /* 顶部拖拽条 + 双击最大化/还原 */',
  '  var bar = document.createElement("div")',
  '  bar.className = "dshkit-dragbar"',
  '  bar.addEventListener("dblclick", function () {',
  '    if (window.__dshDesktop && window.__dshDesktop.windowControl) window.__dshDesktop.windowControl.toggleMaximize()',
  '  })',
  '  document.body.appendChild(bar)',
  '',
  '  var SVG_NS = "http://www.w3.org/2000/svg"',
  '  function makeSvg(inner) {',
  '    var s = document.createElementNS(SVG_NS, "svg")',
  '    s.setAttribute("width", "12")',
  '    s.setAttribute("height", "12")',
  '    s.setAttribute("viewBox", "0 0 12 12")',
  '    s.setAttribute("fill", "none")',
  '    s.innerHTML = inner',
  '    return s',
  '  }',
  '',
  '  /* 最大化状态同步通用函数 */',
  '  function reflectMax(isMax, maxBtn, maxSvg, restoreSvg) {',
  '    var first = maxBtn.firstChild',
  '    if (first && maxSvg) maxBtn.replaceChild(makeSvg(isMax ? restoreSvg : maxSvg), first)',
  '    maxBtn.title = isMax ? "还原" : "最大化"',
  '    maxBtn.setAttribute("aria-label", maxBtn.title)',
  '    document.body.classList.toggle("dshkit-maximized", isMax)',
  '  }',
  '',
  '  if (isMac) {',
  '    /* macOS：左上角信号灯（红=关闭 黄=最小化 绿=最大化/还原） */',
  '    var tl = document.createElement("div")',
  '    tl.className = "dshkit-trafficlights"',
  '    function mkDot(cls, title) {',
  '      var b = document.createElement("button")',
  '      b.type = "button"',
  '      b.className = "dshkit-tl-" + cls',
  '      b.title = title',
  '      b.setAttribute("aria-label", title)',
  '      tl.appendChild(b)',
  '      return b',
  '    }',
  '    var closeBtn = mkDot("close", "关闭")',
  '    var minBtn = mkDot("min", "最小化")',
  '    var maxBtn = mkDot("max", "最大化")',
  '    closeBtn.addEventListener("click", function () {',
  '      if (window.__dshDesktop && window.__dshDesktop.windowControl) window.__dshDesktop.windowControl.close()',
  '    })',
  '    minBtn.addEventListener("click", function () {',
  '      if (window.__dshDesktop && window.__dshDesktop.windowControl) window.__dshDesktop.windowControl.minimize()',
  '    })',
  '    maxBtn.addEventListener("click", function () {',
  '      if (window.__dshDesktop && window.__dshDesktop.windowControl) window.__dshDesktop.windowControl.toggleMaximize()',
  '    })',
  '    if (window.__waitDshDesktop) {',
  '      window.__waitDshDesktop(function (api) {',
  '        if (api.windowControl && api.windowControl.isMaximized) api.windowControl.isMaximized().then(function (v) { reflectMax(v, maxBtn, "", "") })',
  '        if (api.onMaximizedChange) api.onMaximizedChange(function (v) { reflectMax(v, maxBtn, "", "") })',
  '      })',
  '    }',
  '    document.body.appendChild(tl)',
  '  } else {',
  '    /* Windows/Linux：右上角控制按钮 */',
  '    var wrap = document.createElement("div")',
  '    wrap.className = "dshkit-winctl"',
  '    function mk(svgInner, title, cls) {',
  '      var b = document.createElement("button")',
  '      b.type = "button"',
  '      b.title = title',
  '      b.className = "dshkit-" + cls',
  '      b.setAttribute("aria-label", title)',
  '      b.appendChild(makeSvg(svgInner))',
  '      wrap.appendChild(b)',
  '      return b',
  '    }',
  '    var minBtn = mk("<path d=\\"M2 6h8\\" stroke=\\"currentColor\\" stroke-width=\\"1.2\\" stroke-linecap=\\"round\\"/>", "最小化", "min")',
  '    var maxSvg = "<rect x=\\"2.2\\" y=\\"2.2\\" width=\\"7.6\\" height=\\"7.6\\" rx=\\"1\\" stroke=\\"currentColor\\" stroke-width=\\"1.2\\"/>"',
  '    var restoreSvg = "<path d=\\"M4 4V2h6v6H8\\" fill=\\"none\\" stroke=\\"currentColor\\" stroke-width=\\"1.2\\" stroke-linejoin=\\"round\\"/><rect x=\\"2\\" y=\\"4\\" width=\\"6\\" height=\\"6\\" rx=\\"1\\" stroke=\\"currentColor\\" stroke-width=\\"1.2\\"/>"',
  '    var maxBtn = mk(maxSvg, "最大化", "max")',
  '    var closeBtn = mk("<path d=\\"M3 3l6 6M9 3L3 9\\" stroke=\\"currentColor\\" stroke-width=\\"1.2\\" stroke-linecap=\\"round\\"/>", "关闭", "close")',
  '    minBtn.addEventListener("click", function () {',
  '      if (window.__dshDesktop && window.__dshDesktop.windowControl) window.__dshDesktop.windowControl.minimize()',
  '    })',
  '    maxBtn.addEventListener("click", function () {',
  '      if (window.__dshDesktop && window.__dshDesktop.windowControl) window.__dshDesktop.windowControl.toggleMaximize()',
  '    })',
  '    closeBtn.addEventListener("click", function () {',
  '      if (window.__dshDesktop && window.__dshDesktop.windowControl) window.__dshDesktop.windowControl.close()',
  '    })',
  '    if (window.__waitDshDesktop) {',
  '      window.__waitDshDesktop(function (api) {',
  '        if (api.windowControl && api.windowControl.isMaximized) api.windowControl.isMaximized().then(function (v) { reflectMax(v, maxBtn, maxSvg, restoreSvg) })',
  '        if (api.onMaximizedChange) api.onMaximizedChange(function (v) { reflectMax(v, maxBtn, maxSvg, restoreSvg) })',
  '      })',
  '    }',
  '    document.body.appendChild(wrap)',
  '  }',
  '})()',
].join('\n')
